version: 2

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
    nodejs: "18"
  jobs:
    pre_build:
      # Generate API documentation from JSDoc comments before building the docs
      - npm ci
      - mkdir -p docs/api
      - touch docs/api/GeometryEditor.md docs/api/ProjectManager.md  # Create empty files in case generation fails
      - node scripts/generate-api-docs.js
      - ls -la docs/api/  # Debug: List API docs directory contents

python:
  install:
    - requirements: docs/requirements.txt
