version: 2

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
    nodejs: "18"
  jobs:
    pre_build:
      # Ensure API documentation directory exists
      - mkdir -p docs/api
      # Skip the dynamic generation since we now have static API docs
      - echo "Using static API documentation files"
      - ls -la docs/api/  # Debug: List API docs directory contents

python:
  install:
    - requirements: docs/requirements.txt
