version: 2

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
    nodejs: "18"
  jobs:
    pre_build:
      # Generate API documentation from JSDoc comments before building the docs
      - npm install jsdoc jsdoc-to-markdown
      - npm run docs:api
