"""
Material definitions for the g4-editor JSON format.
"""


def get_materials():
    """Return the materials dictionary for all subsystems."""
    return {
        "G4_AIR": {
            "type": "nist",
            "density": 0.00120479,
            "density_unit": "g/cm3",
            "color": [0.9, 0.9, 1.0, 0.05],
        },
        "G4_WATER": {
            "type": "nist",
            "density": 1.0,
            "density_unit": "g/cm3",
            "color": [0.0, 0.4, 0.8, 0.15],
        },
        "G4_Galactic": {
            "type": "nist",
            "density": 1e-25,
            "density_unit": "g/cm3",
            "color": [0.1, 0.1, 0.1, 0.02],
        },
        "G4_Cu": {
            "type": "nist",
            "density": 8.96,
            "density_unit": "g/cm3",
            "color": [0.72, 0.45, 0.2, 0.8],
        },
        "G4_Al": {
            "type": "nist",
            "density": 2.7,
            "density_unit": "g/cm3",
            "color": [0.75, 0.75, 0.75, 0.5],
        },
        "LXe": {
            "type": "element_based",
            "density": 2.862,
            "density_unit": "g/cm3",
            "state": "liquid",
            "temperature": 177.0,
            "temperature_unit": "kelvin",
            "composition": {"Xe": 1},
            "color": [0.094, 0.718, 0.812, 0.15],
        },
        "GXe": {
            "type": "element_based",
            "density": 0.005887,
            "density_unit": "g/cm3",
            "state": "gas",
            "temperature": 177.0,
            "temperature_unit": "kelvin",
            "composition": {"Xe": 1},
            "color": [0.539, 0.318, 0.378, 0.1],
        },
        "SS316Ti": {
            "type": "element_based",
            "density": 8.0,
            "density_unit": "g/cm3",
            "state": "solid",
            "temperature": 293.0,
            "temperature_unit": "kelvin",
            "composition": {"Fe": 65, "Cr": 17, "Ni": 12, "Mo": 3, "Mn": 2, "Ti": 1},
            "color": [0.6, 0.6, 0.6, 0.4],
        },
        "SS304LSteel": {
            "type": "element_based",
            "density": 7.99,
            "density_unit": "g/cm3",
            "state": "solid",
            "temperature": 293.0,
            "temperature_unit": "kelvin",
            "composition": {"Fe": 68, "Cr": 19, "Ni": 10, "Mn": 2, "Si": 1},
            "color": [0.65, 0.65, 0.65, 0.3],
        },
        "PTFE": {
            "type": "element_based",
            "density": 2.2,
            "density_unit": "g/cm3",
            "state": "solid",
            "temperature": 293.0,
            "temperature_unit": "kelvin",
            "composition": {"C": 2, "F": 4},
            "color": [0.95, 0.95, 0.95, 0.8],
        },
        "Kovar": {
            "type": "element_based",
            "density": 8.36,
            "density_unit": "g/cm3",
            "state": "solid",
            "temperature": 293.0,
            "temperature_unit": "kelvin",
            "composition": {"Fe": 54, "Ni": 29, "Co": 17},
            "color": [1.0, 0.486, 0.027, 0.7],
        },
        "Quartz": {
            "type": "element_based",
            "density": 2.2,
            "density_unit": "g/cm3",
            "state": "solid",
            "temperature": 293.0,
            "temperature_unit": "kelvin",
            "composition": {"Si": 1, "O": 2},
            "color": [1.0, 0.757, 0.024, 0.4],
        },
        "Vacuum": {
            "type": "element_based",
            "density": 1e-20,
            "density_unit": "g/cm3",
            "state": "gas",
            "temperature": 293.0,
            "temperature_unit": "kelvin",
            "composition": {"N": 755, "O": 245},
            "color": [0.1, 0.1, 0.1, 0.02],
        },
        "PhotoCathodeAluminium": {
            "type": "element_based",
            "density": 8.0,
            "density_unit": "g/cm3",
            "state": "solid",
            "temperature": 293.0,
            "temperature_unit": "kelvin",
            "composition": {"Al": 1},
            "color": [1.0, 0.082, 0.011, 0.8],
        },
        "Ceramic": {
            "type": "element_based",
            "density": 4.0,
            "density_unit": "g/cm3",
            "state": "solid",
            "temperature": 293.0,
            "temperature_unit": "kelvin",
            "composition": {"Al": 2, "O": 3},
            "color": [0.85, 0.75, 0.55, 0.6],
        },
        "Cirlex": {
            # Polyimide (Kapton-like). Composition C22H10N2O5 per monomer unit.
            "type": "element_based",
            "density": 1.43,
            "density_unit": "g/cm3",
            "state": "solid",
            "temperature": 293.0,
            "temperature_unit": "kelvin",
            "composition": {"C": 22, "H": 10, "N": 2, "O": 5},
            "color": [0.2, 0.5, 0.8, 0.7],
        },
        # --- Neutron veto materials ---
        "Glass": {
            "type": "element_based",
            "density": 2.201,
            "density_unit": "g/cm3",
            "state": "solid",
            "temperature": 168.15,
            "temperature_unit": "kelvin",
            "composition": {"Si": 1, "O": 2},
            "color": [0.8, 0.9, 1.0, 0.3],
        },
        "ePTFE": {
            "type": "element_based",
            "density": 0.5,
            "density_unit": "g/cm3",
            "state": "solid",
            "temperature": 293.0,
            "temperature_unit": "kelvin",
            "composition": {"C": 2, "F": 4},
            "color": [0.95, 0.95, 0.95, 0.6],
        },
    }
