/**
 * Syntax-highlight a JSON string by wrapping tokens in coloured <span> elements.
 *
 * Returns an HTML string intended for use with dangerouslySetInnerHTML.
 * The input **must** be trusted (i.e. generated by JSON.stringify, not
 * arbitrary user HTML) since no escaping beyond what JSON.stringify provides
 * is performed.
 *
 * Colour palette loosely follows VS Code's light theme so it looks natural
 * on a light browser background.
 *
 * @param {string} jsonStr  Pretty-printed JSON string
 * @returns {string}  HTML with <span> wrappers
 */
export function highlightJson(jsonStr) {
  if (!jsonStr) return '';

  // Regex matches JSON tokens in order of priority:
  //  1. strings (keys or string values)
  //  2. numbers
  //  3. booleans
  //  4. null
  const tokenRe = /("(?:\\.|[^"\\])*"(?:\s*:)?)|(\b-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?\b)|(true|false)|(null)/g;

  return jsonStr.replace(tokenRe, (match, str, num, bool, nul) => {
    if (str) {
      // Distinguish keys (string followed by ":") from string values
      if (str.endsWith(':')) {
        // Key — strip the trailing colon, wrap the key, re-add colon
        const key = str.slice(0, -1).trimEnd();
        const colon = ':';
        return `<span style="color:#0451a5">${key}</span>${colon}`;
      }
      // String value
      return `<span style="color:#a31515">${match}</span>`;
    }
    if (num) return `<span style="color:#098658">${match}</span>`;
    if (bool) return `<span style="color:#0000ff">${match}</span>`;
    if (nul) return `<span style="color:#0000ff">${match}</span>`;
    return match;
  });
}
